
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const ADD_NOVEL_REQUEST = 'ADD_NOVEL_REQUEST';
export const ADD_NOVEL_SUCCESS = 'ADD_NOVEL_SUCCESS';
export const ADD_NOVEL_FAILURE = 'ADD_NOVEL_FAILURE';

export const FETCH_TRANSLATORS_REQUEST = 'FETCH_TRANSLATORS_REQUEST';
export const FETCH_TRANSLATORS_SUCCESS = 'FETCH_TRANSLATORS_SUCCESS';
export const FETCH_TRANSLATORS_FAILURE = 'FETCH_TRANSLATORS_FAILURE';

export const FETCH_PUBLISHERS_REQUEST = 'FETCH_PUBLISHERS_REQUEST';
export const FETCH_PUBLISHERS_SUCCESS = 'FETCH_PUBLISHERS_SUCCESS';
export const FETCH_PUBLISHERS_FAILURE = 'FETCH_PUBLISHERS_FAILURE';

export const DELETE_NOVEL_REQUEST = 'DELETE_NOVEL_REQUEST';
export const DELETE_NOVEL_SUCCESS = 'DELETE_NOVEL_SUCCESS';
export const DELETE_NOVEL_FAILURE = 'DELETE_NOVEL_FAILURE';

export const ADD_NOVEL_TO_USER = 'ADD_NOVEL_TO_USER'

